### ISSUE TITLE
Add frontend admin functionality to refresh the laravel cache

### ISSUE THREAD

**Issue by brandtamos** [AlbericTrancart/spacexstats#25]
Front page stats are cached in laravel which is a good thing, but if you want to see changes reflected immediately, you have to SSH into the server and run the "php artisan cache:clear" command. Looks like there is a way to do this in code as well based on this page:
http://laravel-recipes.com/recipes/104/clearing-the-application-cache

Just want to add something to the admin links that allows an admin to clear the cache if needed.

**Comment by jhpratt** [comment]
As this is done in PHP, a conditional could be created with `php artisan cache:clear` in backticks (not sure how to format that). That executes the command. The only thing you'd have to do is make sure the server has the right permissions to run that.

**Comment by brandtamos** [comment]
I think we could call "Cache::flush()" directly in PHP instead of using a shell command call. I'd prefer that if possible, but I also have to add "sudo" before that command any time I run it, so I just need to see  how permissions shake out with that command.

**Comment by jhpratt** [comment]
Ok, not familiar with Laravel, but it certainly sounds like the better option.

**Comment by AlbericTrancart** [comment]
From a security point of view, calling a php function with superuser rights from the front-end is generally considered as a bad idea. That's why I was thinking of a deployment script which will deploy, run the migrations, rebuild the assets and clear the cache with only one command. There are lots of tools to do this, not sure yet which one works best with Laravel.
