### ISSUE TITLE
Merlin Engine Count not calculated correctly

### ISSUE THREAD

**Issue by brandtamos** [AlbericTrancart/spacexstats#9]
It appears that the number of Merlin 1 engines is not being calculated correctly. Right now it stuck at 234 but it should be higher than that.

**Comment by AlbericTrancart** [comment]
Right now it is 261. Maybe a caching issue? Also, how does reusability affect this stat? An engine can be reused accross multiple flights. Maybe we just need to change the wording in order to clear the possible confusion between "built and flown at least once" and "cumulated number of engine flights"

**Comment by brandtamos** [comment]
Yea, I think right now there is no way for us to know if the same engines are flown on a given core during a reflight, though I think that is the assumption. I think for now maybe just changing the wording will suffice. Until they start printing serial numbers on the engines for us to see :)
